-- Teljes adatbázist generáló szkript a truevoly/oracle-12c Docker képfájlhoz (másik 12c verzióval is működhet)
-- A "CREATE INDEX" parancsokat kivettem, mert egyébként is létrejönnek, emiatt hibát dobnak

-- DROP USER FAKEBOOK CASCADE;
-- ^ Ha újra akarod generálni a sémát vedd ki a kommentet a fenti sorból


CREATE USER fakebook
IDENTIFIED BY "fkbU#123"
DEFAULT TABLESPACE users
QUOTA 200M ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO fakebook;

CREATE SEQUENCE FAKEBOOK.COMMENTS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.FRIENDS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.GROUPS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.GROUP_MESSAGES_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.INTERESTS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.MESSAGES_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.POSTS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.USERS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.USER_GROUPS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE SEQUENCE FAKEBOOK.USER_INTERESTS_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE ORDER ;

CREATE TABLE "FAKEBOOK"."USERS" 
   (	"ID" NUMBER(38,0) DEFAULT ON NULL "FAKEBOOK"."USERS_ID_SEQ".NEXTVAL NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE, 
	"FULLNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	"BIRTH_DATE" DATE NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(100) NOT NULL ENABLE, 
	"PICTURE_URL" VARCHAR2(100), 
	"REGISTERED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_LOGIN" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USERS_EMAIL_UNIQUE" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE "FAKEBOOK"."POSTS" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL FAKEBOOK.POSTS_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"TEXT" VARCHAR2(100) NOT NULL ENABLE, 
	"IMAGE_URL" VARCHAR2(100), 
	"AUTHOR_ID" NUMBER(*,0), 
	 CONSTRAINT "POSTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."POSTS" ADD CONSTRAINT "POSTS_USERS_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ENABLE;


CREATE TABLE "FAKEBOOK"."COMMENTS" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL FAKEBOOK.COMMENTS_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"TEXT" VARCHAR2(100) NOT NULL ENABLE, 
	"AUTHOR_ID" NUMBER(*,0), 
	"POST_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."COMMENTS" ADD CONSTRAINT "COMMENTS_POSTS_FK" FOREIGN KEY ("POST_ID")
	  REFERENCES "FAKEBOOK"."POSTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAKEBOOK"."COMMENTS" ADD CONSTRAINT "COMMENTS_USERS_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ENABLE;


CREATE TABLE "FAKEBOOK"."FRIENDS" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL FAKEBOOK.FRIENDS_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PENDING" NUMBER(2,1) DEFAULT 1 NOT NULL ENABLE, 
	"WHEN" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"SENDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"RECEIVER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "FRIENDS_PENDING_CHECK" CHECK (PENDING IN (0, 1)) ENABLE, 
	 CONSTRAINT "FRIENDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."FRIENDS" ADD CONSTRAINT "FRIENDS_USERS_FK" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAKEBOOK"."FRIENDS" ADD CONSTRAINT "FRIENDS_USERS_FK_1" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ON DELETE CASCADE ENABLE;


CREATE TABLE "FAKEBOOK"."GROUPS" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL FAKEBOOK.GROUPS_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



CREATE TABLE "FAKEBOOK"."GROUP_MESSAGES" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL FAKEBOOK.GROUP_MESSAGES_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"TEXT" VARCHAR2(100) NOT NULL ENABLE, 
	"WHEN" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"GROUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SENDER_ID" NUMBER(*,0), 
	 CONSTRAINT "GROUP_MESSAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."GROUP_MESSAGES" ADD CONSTRAINT "GROUP_MESSAGES_GROUPS_FK" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "FAKEBOOK"."GROUPS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAKEBOOK"."GROUP_MESSAGES" ADD CONSTRAINT "GROUP_MESSAGES_USERS_FK" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ENABLE;


CREATE TABLE "FAKEBOOK"."INTERESTS" 
   (	"ID" NUMBER(38,0) DEFAULT ON NULL "FAKEBOOK"."INTERESTS_ID_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "INTERESTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "INTERESTS_NAME_UNIQUE" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE "FAKEBOOK"."MESSAGES" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL "FAKEBOOK"."MESSAGES_ID_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"TEXT" VARCHAR2(100) NOT NULL ENABLE, 
	"WHEN" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"SENDER_ID" NUMBER(38,0), 
	"RECEIVER_ID" NUMBER(38,0), 
	 CONSTRAINT "MESSAGES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."MESSAGES" ADD CONSTRAINT "MESSAGES_USERS_FK" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ENABLE;
  ALTER TABLE "FAKEBOOK"."MESSAGES" ADD CONSTRAINT "MESSAGES_USERS_FK_1" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ENABLE;


CREATE TABLE "FAKEBOOK"."USER_GROUPS" 
   (	"ID" VARCHAR2(100) DEFAULT ON NULL FAKEBOOK.USER_GROUPS_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PENDING" NUMBER(38,0) DEFAULT 1 NOT NULL ENABLE, 
	"ROLE" VARCHAR2(100) DEFAULT 'NORMAL' NOT NULL ENABLE, 
	"USER_ID" NUMBER(*,0), 
	"GROUP_ID" NUMBER(*,0), 
	 CONSTRAINT "USER_GROUPS_PENDING_CHECK" CHECK (PENDING IN (0, 1)) ENABLE, 
	 CONSTRAINT "USER_GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_GROUPS_FK" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "FAKEBOOK"."GROUPS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAKEBOOK"."USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ON DELETE CASCADE ENABLE;

CREATE TABLE "FAKEBOOK"."USER_INTERESTS" 
   (	"ID" NUMBER(*,0) DEFAULT ON NULL "FAKEBOOK"."USER_INTERESTS_ID_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"INTEREST_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "USER_INTERESTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FAKEBOOK"."USER_INTERESTS" ADD CONSTRAINT "USER_INTERESTS_INTERESTS_FK" FOREIGN KEY ("INTEREST_ID")
	  REFERENCES "FAKEBOOK"."INTERESTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAKEBOOK"."USER_INTERESTS" ADD CONSTRAINT "USER_INTERESTS_USERS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "FAKEBOOK"."USERS" ("ID") ON DELETE CASCADE ENABLE;
